---
tzx-changes:
  - hash: 624fca16ab754c62ba0a2719873dc9aac7dc9900
    datetime: 1493994149
    insertions: 251
    deletions: 0

tzx-filename: ...69-gis-spatial-analysis-application-modeling.md
...
